// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://pkyzgxezmqhmwegfkahy.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBreXpneGV6bXFobXdlZ2ZrYWh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI3MDE0ODcsImV4cCI6MjA0ODI3NzQ4N30.OHvtjDWZ-SAXEOFtalEM92AGuAshSBwZi_a-D90MDFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);